/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.lordlee;

import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Widget extends javax.swing.JFrame {

    public String OS = "";
    int xMouse;
    int yMouse;
    ImageIcon ImageIcon = new ImageIcon("src/de/lordlee/shutdown.png");
    public Image Image = ImageIcon.getImage();
    
    public Widget() {
        initComponents();
        
        
        OS = System.getProperty("os.name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        Draggable = new javax.swing.JLabel();
        shutdown = new javax.swing.JLabel();
        restart = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        abort = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Image);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(328, 105));
        setMinimumSize(new java.awt.Dimension(328, 105));
        setName("Widget"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(328, 105));
        setResizable(false);
        setSize(new java.awt.Dimension(328, 105));

        Panel.setBackground(new java.awt.Color(102, 0, 0));
        Panel.setForeground(new java.awt.Color(204, 0, 0));
        Panel.setMaximumSize(new java.awt.Dimension(328, 105));
        Panel.setMinimumSize(new java.awt.Dimension(328, 105));
        Panel.setPreferredSize(new java.awt.Dimension(328, 105));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        x.setText("x");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                xMouseReleased(evt);
            }
        });
        Panel.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 16, 23));

        Draggable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DraggableMouseDragged(evt);
            }
        });
        Draggable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DraggableMousePressed(evt);
            }
        });
        Panel.add(Draggable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 20));

        shutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/lordlee/shutdown.png"))); // NOI18N
        shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                shutdownMouseReleased(evt);
            }
        });
        Panel.add(shutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        restart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/lordlee/restart.png"))); // NOI18N
        restart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                restartMouseReleased(evt);
            }
        });
        Panel.add(restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/lordlee/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        Panel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        abort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/lordlee/abbruch.png"))); // NOI18N
        abort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                abortMouseReleased(evt);
            }
        });
        Panel.add(abort, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseReleased
        System.exit(0);
    }//GEN-LAST:event_xMouseReleased

    private void DraggableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggableMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_DraggableMouseDragged

    private void DraggableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggableMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_DraggableMousePressed

    private void shutdownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdownMouseReleased
        String commandExec = "";
        if (OS.contains("Windows")){
        commandExec = "shutdown -s -t 60";
        }else if (OS.contains("Linux")){
        commandExec = "shutdown -h +1";
        }else if (OS.contains("Mac")){
        commandExec = "shutdown -h +1";
        }else {
            JOptionPane.showMessageDialog(rootPane, "OS not supported yet. Contact lordlee.de.");
        }
        try
        {
            Runtime.getRuntime().exec(commandExec);
        }
        catch(IOException e )
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_shutdownMouseReleased

    private void restartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseReleased
        String commandExec = "";
        if (OS.contains("Windows")){
        commandExec = "shutdown -r -t 60";
        }else if (OS.contains("Linux")){
        commandExec = "shutdown -r +1";
        }else if (OS.contains("Mac")){
        commandExec = "shutdown -r +1";
        } else {
            JOptionPane.showMessageDialog(rootPane, "OS not supported yet. Contact lordlee.de.");
        }
        try
        {
            Runtime.getRuntime().exec(commandExec);
        }
        catch(IOException e )
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_restartMouseReleased

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        String commandExec = "";
        if (OS.contains("Windows")){
        commandExec = "shutdown -l";
        }else if (OS.contains("Linux")){
        commandExec = "kill -9 -1";
        }else if (OS.contains("Mac")){
        commandExec = "osascript -e 'tell app \"System Events\" to log out'";
        } else {
            JOptionPane.showMessageDialog(rootPane, "OS not supported yet. Contact lordlee.de.");
        }
        try
        {
            Runtime.getRuntime().exec(commandExec);
        }
        catch(IOException e )
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_logoutMouseReleased

    private void abortMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abortMouseReleased
        String commandExec = "";
        if (OS.contains("Windows")){
        commandExec = "shutdown -a";
        }else if (OS.contains("Linux")){
        commandExec = "shutdown -c";
        }else if (OS.contains("Mac")){
        commandExec = "sudo killall shutdown";
        } else {
            JOptionPane.showMessageDialog(rootPane, "OS not supported yet. Contact lordlee.de.");
        }
        try
        {
            Runtime.getRuntime().exec(commandExec);
        }
        catch(IOException e )
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_abortMouseReleased

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Draggable;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel abort;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel restart;
    private javax.swing.JLabel shutdown;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables

    
}
